Tri 209/refactor ticket data fetching on ticket interaction
sirius-valley/tricker-front pull request #132
Opened 2024-04-08 15:56 UTC by matiaspizzi

# Pull Request

## Description
When changing the selected ticket, data fetching in TicketDetail component will be done, retrieving the issue detail (description and labels).
Also I unified TiketList and TicketListSmallDisplay into one unique component with a variant prop "list" or "grid".

## Ticket Link
[[TRI-209]](https://linear.app/tricker-sirius/issue/TRI-209/refactor-ticket-data-fetching-on-ticket-interaction)

2024-04-09 16:13 UTC, FedericoMartucci reviewed
When ticket info is being fetched it appears this text and the "ticket info" skeleton does not occupies the full width and it seems weird.
<img width="736" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/3dc67d1e-9eaf-4129-b296-755a21a94bf5">

After the info is fetched the chronology is still loading. I think that it is because this info comes from another endpoint. However, the chronology info is already in the ticket display endpoint (check the 2nd picture), so you can take that info from that endpoint avoiding to make 2 requests to the BE. 
<img width="724" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/82aae9d0-ff74-45e5-aa19-d3468dfe99d0">
<img width="915" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/d09db091-8698-4c3d-bd58-96f9a6e7af30">

2024-04-11 12:46 UTC, FedericoMartucci requested changes
There are two remaining things:
- It is still showing "Chronology" title in both mobile and desktop.
- The skeleton loader width for mobile has to be fixed, check how it is shown in the video below.

https://github.com/sirius-valley/tricker-front/assets/112835662/bfb0758e-7174-423e-b98f-3063f5615410

2024-04-11 14:32 UTC, matiaspizzi commented
![image](https://github.com/sirius-valley/tricker-front/assets/87399661/5daffe16-e89f-40e3-9e0b-5825d67d9f6c)

2024-04-11 15:07 UTC, FedericoMartucci approved these changes

2024-04-11 16:02 UTC, merged