TRI-186/Project-Listening-w-Selection-Highlight
sirius-valley/tricker-front pull request #135
Opened 2024-04-10 05:12 UTC by KevNic96

# Pull Request

## Description
Create a component that lists all the user's projects and visually distinguishes the currently selected project by highlighting it in green. This list will be interactive, allowing the user to select and switch between projects easily.

## Ticket Link
[[TRI-186](https://linear.app/tricker-sirius/issue/TRI-186/project-listing-with-selection-highlight)]

## Steps to Reproduce
1. npm run storybook
2. Go to Components/MyProjectSelection
3. Check how it looks with 4 or less components in desktop and mobile, and then, to see how it looks with a lot of projects (just in case) copy and paste this: 

```
,
      {
        id: '5',
        title: 'Bonterms',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '6',
        title: 'Tricker',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '7',
        title: 'Hospital Patagonia',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '8',
        title: 'Bonterms',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '9',
        title: 'Tricker',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '10',
        title: 'Hospital Patagonia',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '11',
        title: 'Bonterms',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '12',
        title: 'Tricker',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '13',
        title: 'Bonterms',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '14',
        title: 'Tricker',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '15',
        title: 'Hospital Patagonia',
        image: 'https://via.placeholder.com/20'
      },
      {
        id: '16',
        title: 'Bonterms',
        image: 'https://via.placeholder.com/20'
      }
```

## Images/Screenshots (if necessary)
Desktop:
![image](https://github.com/sirius-valley/tricker-front/assets/99856968/0c8bc9ef-ae90-4b11-bf42-cf7177c0e55c)

Mobile:
![image](https://github.com/sirius-valley/tricker-front/assets/99856968/e16f05a6-c57b-4758-b1af-790d7238077f)

## Additional Notes (if any)
In mobile, I couldn't change the bg to gray-500 cause the gradiant of the desktop design, and also in mobile the scrollbar when there are more than 4 projects looks bad and I couldn't find the solution to it.
I'm open to any improvement of the component

2024-04-10 14:21 UTC, FedericoMartucci requested changes
Finally, with all the fixes done, try to change the bg-color to bg-gray-500 as it should be.

2024-04-10 14:21 UTC, FedericoMartucci commented on src/components/MyProjectSelection/MyProjectSelection.tsx
> +      ></div>
The behaviour of the gradient should be something similar to this:
<img width="574" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/f4a74f86-6aa9-499c-be66-34e289aaf7ce">
And we have this:
<img width="431" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/b9f9eded-70af-491c-acf2-552f9490b276">
Check `from-gray-500 via-gray-600 to-gray-600`, you can set an opacity to display what is under that div doing this:
`from-gray-500/10 via-gray-600/50 to-gray-600/80` adding `/number` at the end you will be setting the opacity that the color will have, in the example '/10' represents 10% opacity, '/80' = %80, etc. Check what opacity number will adapt better to the design achieving a smooth gradient.
Another point is that `${isMobile ? 'z-0 bg-gray-500 rounded-lg' : 'rounded-bl-lg'}` is setting a background color removing the gradient, delete the 'bg-gray-500' property. Also the scrollbar is being affected by the gradient, you can just change `w-full` by `w-[calc(100% - (<scrollbar width>))]`
Be careful with the gradient because it does not allow you to select an item if you click on it. Try to fix that problem.

2024-04-10 14:21 UTC, FedericoMartucci commented on src/components/MyProjectSelection/MyProjectSelection.tsx
> +  )
I do not agree with this logic. I would rather to store in redux dropdown options (projects) and retrieve them to take them and work with real info. In other case, the parent component will be overloaded of logic that is responsability of this component. In conclusion, I would implement logic to retrieve projects from redux instead of depending on a prop.

2024-04-10 14:21 UTC, FedericoMartucci commented on src/components/MyProjectSelection/MyProjectSelection.tsx
> +    useState<MyProjectsOption>(preselectedOption)
You can retrieve the currentProjectId from redux, it is already implemented and after that you can make an Array.find to obtain the missing info (title and image). Check that in mobile the project does not have to be preselect because it will open the modal with the info of the project and that's not the idea.
It should look like this:
<img width="573" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/43b5e625-f62b-418f-a72b-29e2894076a7">

2024-04-10 14:21 UTC, FedericoMartucci commented on src/components/MyProjectSelection/MyProjectSelection.tsx
> +      >
It does not have sense to do `options.length > 12 ? 'h-[calc(100%-131px)]` why do you want to adjust the height to maintain the info above the gradient? that is not the idea.

2024-04-10 14:21 UTC, FedericoMartucci commented on src/components/MyProjectSelection/MyProjectSelection.tsx
> +            >
When I click an element the content of the list item is moving 2px to the right.
<img width="437" alt="image" src="https://github.com/sirius-valley/tricker-front/assets/112835662/1455c9e5-0720-4379-86fd-ec84f442273e">

2024-04-11 21:59 UTC, KevNic96 commented on src/components/MyProjectSelection/MyProjectSelection.tsx
> +      ></div>
when I use `w-[calc(100% - (<scrollbar width>))]` the scrollbar looks fine, but the gradient dissapears, I tried to use another options but I couldn't find the way to solve it

2024-04-13 21:51 UTC, FedericoMartucci approved these changes

2024-04-15 14:28 UTC, matiaspizzi approved these changes

2024-04-15 14:31 UTC, merged