TRI-216/Implement Infinite Scroll w Pagination for Card Fetching
sirius-valley/tricker-front pull request #147
Opened 2024-04-18 15:40 UTC by KevNic96

# Pull Request

## Description
Incorporate an infinite scroll mechanism into the front end to enhance user experience by loading cards as the user scrolls. The fetching should be efficiently managed with pagination, loading 10 cards at a time.

## Ticket Link
[[TRI-216]](https://linear.app/tricker-sirius/issue/TRI-216/implement-infinite-scroll-with-pagination-for-card-fetching)

## Steps to Reproduce
1. Integrate a project and run BE
2. `npm run dev`
3. Check Team Section and how the scrollbar works in desktop and mobile (it also might work in Home Section)

## Images/Screenshots
![image](https://github.com/sirius-valley/tricker-front/assets/99856968/e45a3259-07ef-43af-8956-5640701cba10)

## Additional Notes
I didn't get how to do the Seamless Loading task, if anyone know, I would appreciate the help!

2024-04-18 15:59 UTC, FedericoMartucci requested changes
There are a few things that need to be reviewed:
- The main task of the card was to perform an infinite scroll and it's not working.
- The scrollbar is not necessary since it doesn't align with the Figma design.
- The backend returns 5 cards at a time, so the limit sent by query param is not necessary.

To fix this, you need to do the following:
1. Using the useRef hook, we need to reference the last card that the user views and save that ticketId (it will be our cursor).
2. Handle that when the user reaches the bottom of the scroll, a request is made to the backend sending that id as the cursor in the body.
3. While the above occurs, display a loader below the preloaded cards indicating to the user that new ones are being loaded (this is possible thanks to isLoading returned by the useQuery hook we use to handle requests).
4. If the backend brings back less than 5 cards, it means there are no more cards to display, so with a variable 'hasMore' or something similar, we must control this to avoid unnecessary requests.

2024-04-26 12:47 UTC, FedericoMartucci submitted a review, later dismissed
Infinite scroll for web is OK, but for mobile is not working:

https://github.com/sirius-valley/tricker-front/assets/112835662/185920ff-7347-4543-b047-9567875727fc

2024-04-29 13:25 UTC, matiaspizzi approved these changes

2024-04-29 14:01 UTC, matiaspizzi approved these changes

2024-04-29 14:03 UTC, merged